### ISSUE TITLE
Great software

### ISSUE THREAD

**Issue by charlesrg** [DirkReiners/LEDBadgeProgrammer#1]
We are very excited that you wrote this library and also looking to get our min display to program the displays in Linux. 
We are running into this issue, have you seen this before ?

```
[root@box] /tmp/LEDBadgeProgrammer # python --version
Python 2.6.6
[root@box] /tmp/LEDBadgeProgrammer # python ledbadge.py speed=5 marquee=on halign=center "Fireworks"
Sending message(s):
Traceback (most recent call last):
  File "ledbadge.py", line 419, in <module>
    b.send()
  File "ledbadge.py", line 305, in send
    ser = serial.Serial(self._port, 4800)
  File "/usr/lib/python2.6/site-packages/serial/serialutil.py", line 182, in __init__
    self.open()
  File "/usr/lib/python2.6/site-packages/serial/serialposix.py", line 249, in open
    self._reconfigure_port(force_update=True)
  File "/usr/lib/python2.6/site-packages/serial/serialposix.py", line 308, in _reconfigure_port
    ispeed = ospeed = getattr(termios, 'B{}'.format(self._baudrate))
ValueError: zero length field name in format

```

Not sure if its because of Centos 6 old python or something that we can work around.

**Comment by DirkReiners** [comment]
Hm, that looks like your serial lib is for 2.7 but you're running 2.6. Can you check if you have at least python 2.7 on the system, (try running python2.7 and see what it says)? If you do, try running it explicitly as python 2.7 ledbadge.py ...

Hope it helps!

Source: http://stackoverflow.com/questions/5446964/valueerror-zero-length-field-name-in-format-error-in-python-3-0-3-1-3-2

**Comment by charlesrg** [comment]
Thanks all good.
[root@box2] /usr/src/LEDBadgeProgrammer # python -V
Python 2.7.5
[root@box2] /usr/src/LEDBadgeProgrammer # python ledbadge.py speed=8 effect=left "NY7LPHV1" invert=on " NY7LPHV1 "
Sending message(s): Header sent... Image lines = = = = = = = = = = = =
All done!
