### ISSUE TITLE
having trouble :(

### ISSUE THREAD

**Issue by TheLisaRei** [DirkReiners/LEDBadgeProgrammer#3]
Hi,
the tool goes off as if it went through, but nothing happens on the badge. With all the commands it is the same, no errors but does not work. 

example:
python ledbadge.py test_12x48.png
Sending message(s): Header sent... Image lines = = = = = = = = = = = = 
All done!

operating system: debian bullseye, python: 2.7

(it works with https://github.com/stoggi/ledbadge but that is only text, yours has image capabilities/fonts/etc. so I'd love to get yours working)

Thank you so much!!!

**Comment by DirkReiners** [comment]
Hi Lisa,

sorry, I haven't had a chance to work on that in a long time. They changed
the controllers on the badges, and the latest batch I bought didn't work
any more with my script. :( Not sure if/when I'll have time to work on
that...

Sorry about that

  Dirk

**Comment by TheLisaRei** [comment]
Thank you! 
I decided to buy new ones with a bluetooth app!
Cheers <3
